EDU-4926: disable Rust integration for Rust plugin builds before 0.4.165 starting from 2021.3
It should prevent `NoSuchMethodError` with old Rust plugin versions

(cherry picked from commit 15ab26dd9da2b649bbb2be35d9d15836f427a46c)