EDU-5608: fix compatibility issue with Rust plugin
`CargoCommandLine` constructor was changed in 0.4.188. As a result, signature of `CargoCommandLine.copy` was changed as well which causes `NoSuchMethodError` if plugin is build with incompatible plugin version

These changes:
- update Rust plugin version used for compilation
- increase minimal supported Rust plugin version in `RsConfigurator` for 223 and 231 platforms

(cherry picked from commit 9414d628f7014c44f4be8b54f69f903002a18abd)