Exclude gson from plugin archive
The platform already contains gson library so we don't need to use own one and increase plugin archive size.
Also, it fixes checker tests in Edu-Rust module because Rust plugin relies on platform Gson (that is newer that Edu plugins has) and they fail with `NoSuchMethodError` because of weird classloading in tests