Add workaround to fix tests in `Edu-JavaScript` module
Temporarily use 252 beta builds to avoid
```
java.lang.ClassCastException: class k.k.k.k.w cannot be cast to class com.intellij.openapi.startup.StartupActivity (k.k.k.k.w and com.intellij.openapi.startup.StartupActivity are in unnamed module of loader 'app')
```

error in tests with 252 RC

(cherry picked from commit 6b596c8f2680bf2357f3544b28c92e4519e1b21c)