EDU-4600: add optional dependency on android plugin back
Needs to avoid unexpected `NoClassDefFoundError`

(cherry picked from commit cb53258b211db155dc49988551e182b276ccd7fe)