EDU-6866: fix `java.lang.NoClassDefFoundError: org/opentest4j/AssertionFailedError`
Starting from 242.16677, opentest4j cannot be found in classpath during test for some reason (it seems it's connected to https://youtrack.jetbrains.com/issue/IJPL-156277). As a temporary solution - add test dependency on opentest4j lib manually

(cherry picked from commit 36129168515a92ccbfe4dcad87e53d83b85bf266)