EDU-6903: fix `NoSuchMethodError` with latest Rust plugin versions
These changes introduce workaround to fix changes in `RsToolchainPathChoosingComboBox` API. Mostly it's about overcoming dropping of `callback` when loading toolchain ends to properly validate data in Rust language settings

(cherry picked from commit 8c8ffb1372f80ed9efd9aa1ad58544141df9698f)